atlas-api/src/main/java/org/atlasapi/output/annotation/ExtendedDescriptionAnnotation.java, atlas-cassandra/src/main/java/org/atlasapi/content/RestrictionSerializer.java, atlas-cassandra/src/main/protobuf/content.proto, atlas-cassandra/src/test/java/org/atlasapi/content/RestrictionSerializerTest.java, atlas-core/src/main/java/org/atlasapi/content/Restriction.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyContentTransformer.java
Add ratings authority and their rating.
=> Port restriction model changes from owl

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsBroadcast.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTranslator.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsLocation.java
- Used DateTime constructor to make parsing of date as generic as possible (it will accept as input an instance of Date, String, Long, etc)
=> Fixed bug where an object of type map was cast to String

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/output/BroadcastMergingTest.java
Instead of taking broadcasts from the chosen one, find
the most precedent item to take them from.
=> Use broadcasts from most precedent item

atlas-core/src/main/java/org/atlasapi/content/ContentIndex.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContent.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndex.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndexer.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/InstrumentedContentIndex.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/PseudoEquivalentContentIndex.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexTest.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
Not merge ready, needs wiring in, but for your eyes
=> Create worker, logic for updating canonicals, and tests

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java, atlas-cassandra/src/main/java/org/atlasapi/CassandraPersistenceModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java, atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
- Created null message sending equivalent content store and wired into ContentBootstrapController.java and ContentDebugController.java
=> Changed bootstrap/debug controllers to not send messages to Kafka

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java
- Graph column is only being used to ensure consistency between the
equivalent_content and equivalent_content_index stores. However we
accept eventual consistency anyway and also if the data is
inconsistent the existing code does not log or attempt to resolve the
issue. Therefore it is safe to stop using this column.
- Large batch updates to C* that are due to this graph column are a
likely cause of C* instability
- Remove duplicate updates of equivalent_content rows
=> Remove unnecessary graph column from equivalent_content store

atlas-api/src/main/java/org/atlasapi/output/annotation/ChannelGroupAdvertisedChannelsAnnotation.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java, atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java
1.deleted query for channel_groups
2.added annotation to the advertised channel_groups
=> Added new annotation advertised_channels

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java, atlas-cassandra/src/main/java/org/atlasapi/CassandraPersistenceModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java, atlas-processing/src/test/java/org/atlasapi/system/bootstrap/ContentBootstrapListenerTest.java
- ContentBootstrapListener can optionally bootstrap equivalents
- Create null message sending equivalence graph store
=> Allow for bootstrapping source plus equivalents to that source

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndexer.java
- When deleting stale ES entries do not delete entries of the
same type as the currently indexed Content to avoid losing data
denormalised on series by episodes, e.g. locations and broadcasts
=> Only delete stale ES entries of a different type than the current one

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java, atlas-cassandra/src/test/java/org/atlasapi/content/CassandraEquivalentContentStoreRowIT.java
- The four batch statements should be safe to merge since only one of
one of them contains particularly large statements
- Delete failing test that is no longer useful. With the deprecation
of the graph column, if an equivalent_content row also has an empty
data column then it has no useful information whatsoever and whether
it resolves or not is immaterial
=> Merge batch statements to eliminate possible race conditions

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
- This is intended to deal with transient C* failures
=> Retry on content bootstrap failures

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
- This is non recoverable failure that is indefinitely blocking the
queues
=> Do not mark MissingResourceException as recoverable

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
- There is currently a C* tombstone issue that means retrying on
those timeouts starves the queue
=> Disable retrying on OperationTimeoutException for content bootstrap

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java, atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
- Add support for migrating equivalents when migrating containers
=> Add support for migrating equivalents to ContentDebugController

atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
When updating equivalences, if a corrupted graph was detected, the graph store would clear it and retry the update. The retry was being done via recursion and the lock used is not reentrant, which causes a deadlock. This hacks around it by unlocking before recursing.
=> Fix deadlock in `AbstractEquivalenceGraphStore`.

atlas-elasticsearch/pom.xml, atlas-elasticsearch/src/main/java/org/atlasapi/ElasticSearchContentIndexModule.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndex.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsContentSearcherV3CompatibilityTest.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsContentTitleSearcherTest.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexTest.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexingTest.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/PseudoEquivalentContentIndexIT.java, atlas-elasticsearch/src/test/java/org/atlasapi/topic/EsPopularTopicsIndexTest.java, atlas-elasticsearch/src/test/java/org/atlasapi/util/ElasticSearchHelper.java
Reverts atlasapi/atlas-deer#235
=> Revert "Sort ES hits according to publisher precedence using groovy script"

atlas-api/src/main/java/org/atlasapi/application/auth/ApiKeySourcesFetcher.java, atlas-api/src/test/java/org/atlasapi/application/auth/ApiKeySourcesFetcherTest.java
https://jira.metabroadcast.com/browse/MBST-13668
This will allow users to set an api key in a header
=> Api key from header

atlas-api/src/main/java/org/atlasapi/application/auth/ApiKeySourcesFetcher.java
Reverts atlasapi/atlas-deer#238
=> Revert "api key deleted from the list of required parameters"

atlas-api/src/main/java/org/atlasapi/application/auth/ApiKeySourcesFetcher.java
Reverts atlasapi/atlas-deer#239
=> api key deleted from the list of required parameters

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java
In the case that there are multiple items from the source
whose broadcasts are chosen as precedent, all broadcasts
from that source should be output, not just those from the
most precedent item.
It is assumed that within a data source, broadcasts aren't
duplicated, hence this is a valid approach. Otherwise, in the
case of multiple items from the same source being in an
equivalent set, some broadcasts will, erroneously, be omitted.
One such case is Press Association which may have generic
episodes for a show, alongside full hierarchical data.
=> Output all broadcasts from the source chosen for broadcasts

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java
- If the content that a set is named after fails to resolve then
there might not be a mapping from the set ID to itself in the equiv
content index. This will create the peculiar situation of not being
able to resolve an equiv set by asking for it with its canonical ID.
=> Ensure there is a mapping from a set to itself in the equiv index

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java
- getGraphUpdateRows does not need to compute a unique set of graphs
since the input graphs should be unique anyway
- Change getUpdateIndexRows so that it collects potentially duplicate
IDs in a set rather than a map
=> Fix duplicate keys breaking Collectors.toMap

atlas-api/src/main/java/org/atlasapi/query/v4/organisation/OrganisationController.java
Reverts atlasapi/atlas-deer#254
=> Revert "deleted unnecessary variables from get endpoint"

atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorkerTest.java
Reverts atlasapi/atlas-deer#252
=> Revert "fix test"

atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyChannelTransformer.java
Reverts atlasapi/atlas-deer#255
=> Revert "Removed setAdvertiseFrom in toBasicLegacyChannel in LegacyChannelTran…"

atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorkerTest.java
Reverts atlasapi/atlas-deer#257
=> "fix test"

atlas-api/src/main/java/org/atlasapi/query/v4/organisation/OrganisationController.java
Reverts atlasapi/atlas-deer#256
=> deleted unnecessary variables from get endpoint

atlas-cassandra/src/main/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStore.java, atlas-cassandra/src/test/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStoreIT.java, atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java, atlas-core/src/test/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStoreTest.java
- Due to past bugs we could have stale index entries that point to an
equivalence graph that does not actually contain the resource ID in
question. This will prevent resolution of the graph from the stale
index and will instead return absent, i.e. that a graph has not been
found for the requested resource ID
- Also this removes the code in AbstractEquivalenceGraphStore that
was attempting to handle this issue by deleting the "corrupt" graph
because the graph that is resolved from the stale index is not
necessarily a bad one. At that point all we know is that it should
not have been resolved for that particular requested resource ID
=> Do not resolve equivalence graphs from stale index entries

atlas-api/src/main/java/org/atlasapi/output/writers/ContainerSummaryWriter.java, atlas-api/src/main/java/org/atlasapi/output/writers/SeriesSummaryWriter.java, atlas-api/src/main/java/org/atlasapi/query/QueryModule.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/main/java/org/atlasapi/query/v4/content/IndexBackedEquivalentContentQueryExecutor.java, atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java, atlas-cassandra/src/test/java/org/atlasapi/content/CassandraEquivalentContentStoreRowIT.java, atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java, atlas-core/src/main/java/org/atlasapi/content/ContainerSummaryResolver.java, atlas-core/src/main/java/org/atlasapi/content/MergingEquivalentsResolverBackedContainerSummaryResolver.java, atlas-core/src/main/java/org/atlasapi/equivalence/AnnotationBasedMergingEquivalentsResolver.java, atlas-core/src/main/java/org/atlasapi/equivalence/EquivalentsResolver.java, atlas-core/src/test/java/org/atlasapi/content/MergingEquivalentsResolverBackedContainerSummaryResolverTest.java
1.Added new annotation
2.With the new annotation content is not being merged
3.Fix passing nulls
=> Returning non-merged content

atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
- We were not passing the requested id in...
=> Fix broken equivalent content endpoint and add endpoint to get eq. set

atlas-core/src/main/java/org/atlasapi/content/AbstractEquivalentContentStore.java
- The lock used in AbstractEquivalentContentStore is not reentrant
which can cause a deadlock when updating stale content during a graph
deletion. The ID(s) of the deleted graph(s) will be in the locked
IDs, but could also be among the stale content IDs which will cause
the thread to block itself when it tries to lock them before
updating stale content
=> Prevent deadlock in AbstractEquivalentContentStore

atlas-core/src/main/java/org/atlasapi/topic/Topic.java, atlas-processing/src/main/java/org/atlasapi/system/debug/EventDebugController.java, atlas-processing/src/test/java/org/atlasapi/system/debug/EventDebugControllerTest.java
2.Removed methods reimplemented in topic that were causing problems during deserialozation
=> 1.Added test for debug controller

atlas-api/src/main/java/org/atlasapi/output/annotation/EventDetailsAnnotation.java, atlas-api/src/main/java/org/atlasapi/query/QueryModule.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/main/java/org/atlasapi/query/v4/event/EventController.java, atlas-api/src/main/java/org/atlasapi/query/v4/event/EventListWriter.java, atlas-api/src/main/java/org/atlasapi/query/v4/event/EventQueryExecutor.java, atlas-api/src/main/java/org/atlasapi/query/v4/event/EventQueryResultWriter.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyEventV2Transformer.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyOrganisationTransformer.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyEventTransformerTest.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyEventV2TransformerTest.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyOrganisationResolverTest.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyOrganisationTransformerTest.java
2.Added uri as alias for events and organisations
=> 1.Pointing api to the new store

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java
- Not calling start(), shutdown() on PostConstruct, PreDestroy causes
an NPE due to the underlying BackgroundComputingValue not
instantiating properly
=> Call start(), shutdown() on CachingChannelStore

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
=> Due to a typo the override schedules weren't being merged in

atlas-api/src/main/java/org/atlasapi/application/ApplicationsController.java, atlas-api/src/main/java/org/atlasapi/application/SourceLicenseController.java, atlas-api/src/main/java/org/atlasapi/application/SourceRequestsController.java, atlas-api/src/main/java/org/atlasapi/application/SourcesController.java, atlas-api/src/main/java/org/atlasapi/application/auth/NoAuthUserFetcher.java, atlas-api/src/main/java/org/atlasapi/application/auth/www/AuthController.java, atlas-api/src/main/java/org/atlasapi/application/users/EndUserLicenseController.java, atlas-api/src/main/java/org/atlasapi/application/users/UsersController.java, atlas-api/src/main/java/org/atlasapi/application/www/ApplicationWebModule.java, atlas-api/src/main/java/org/atlasapi/query/common/useraware/StandardUserAwareQueryParserNoAuth.java, atlas-api/src/main/java/org/atlasapi/query/common/useraware/UserAwareQueryContextParserNoAuth.java, atlas-core/src/main/java/org/atlasapi/application/users/CacheBackedUserStore.java, atlas-core/src/main/java/org/atlasapi/application/users/LegacyAdaptingUserStore.java, atlas-core/src/main/java/org/atlasapi/application/users/UserStore.java
-Added user fetcher, that is fetching by email
-Added nonauth query parser
-Duplicated endpoints with no auth
=> Added nonaouth versions for endpoints

atlas-api/src/main/java/org/atlasapi/application/users/UsersController.java
- User A should have permission to edit user B if A == B OR if user A
is an admin
=> Fix user permission checking

atlas-legacy/src/main/java/org/atlasapi/system/legacy/BaseLegacyResourceTransformer.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyCrewMemberTransformer.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyCrewMemberTransformerTest.java
work with Owl CrewMembers without IDs
=> MBST-15350: LegacyContentTransformer:  CrewMember transform to 

atlas-api/src/main/java/org/atlasapi/messaging/KafkaMessagingModule.java, atlas-api/src/main/resources/config/environment.properties, atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
- This will save failed messages to mongo and retry them periodically
- Also refactor worker modules to have a consistent code style
=> Add persistent retry policy to all Kafka consumers

atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java, atlas-cassandra/src/main/java/org/atlasapi/content/ContentSerializationVisitor.java, atlas-cassandra/src/main/java/org/atlasapi/entity/DescribedSerializer.java, atlas-cassandra/src/main/java/org/atlasapi/entity/RatingSerializer.java, atlas-cassandra/src/main/java/org/atlasapi/entity/ReviewSerializer.java, atlas-cassandra/src/main/protobuf/common.proto, atlas-cassandra/src/main/protobuf/content.proto, atlas-cassandra/src/test/java/org/atlasapi/content/ContentGroupSerializerTest.java, atlas-cassandra/src/test/java/org/atlasapi/content/ContentSerializerTest.java, atlas-core/src/main/java/org/atlasapi/content/Described.java, atlas-core/src/main/java/org/atlasapi/entity/Rating.java, atlas-core/src/main/java/org/atlasapi/entity/Review.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/DescribedLegacyResourceTransformer.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyContentTransformerTest.java
* added fields to Described
* LegacyTransformer understands reviews and ratings
* Described serialiser understands ratings/reviews
* Described serialiser understands ratings/reviews for content_group
=> MBST-14272: added Reviews/Ratings:

atlas-legacy/src/main/java/org/atlasapi/system/legacy/DescribedLegacyResourceTransformer.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyContentTransformer.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyContentTransformerTest.java
Not ready for merge, but appreciate comments and thoughts about my mass commenting out and replumbing fest.  Tests are passing (but coverage is low)
=> Mbst 15396 fix clip legacy importer

atlas-api/src/main/java/org/atlasapi/output/annotation/ClipsAnnotation.java, atlas-api/src/main/java/org/atlasapi/output/writers/ClipsWriter.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
=> MBST-15472: Extend Clips annotation to include locations

atlas-api/src/main/java/org/atlasapi/output/annotation/RatingsAnnotation.java, atlas-api/src/main/java/org/atlasapi/output/annotation/ReviewsAnnotation.java, atlas-api/src/main/java/org/atlasapi/output/writers/RatingsWriter.java, atlas-api/src/main/java/org/atlasapi/output/writers/ReviewsWriter.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/test/java/org/atlasapi/output/writers/RatingsWriterTest.java, atlas-api/src/test/java/org/atlasapi/output/writers/ReviewsWriterTest.java, atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java, atlas-cassandra/src/main/java/org/atlasapi/entity/DescribedSerializer.java, atlas-cassandra/src/main/java/org/atlasapi/entity/ReviewSerializer.java, atlas-cassandra/src/test/java/org/atlasapi/content/ContentGroupSerializerTest.java, atlas-cassandra/src/test/java/org/atlasapi/content/ContentSerializerTest.java, atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java, atlas-core/src/main/java/org/atlasapi/entity/Review.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/DescribedLegacyResourceTransformer.java, atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyContentTransformerTest.java
note:
* Ratings have sources.
todo:
* Reviews do not have sources (in Owl Reviews inherit source from content).  Need to add same inherit functionality
=> MBST-15486: Add Reviews and Ratings to API

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java
All needs to do is concatenate all the items for equivs together.
=> Mbst 15522 merge ratings and reviews in output

atlas-api/src/main/java/org/atlasapi/application/ApplicationsController.java, atlas-api/src/main/java/org/atlasapi/application/SourceRequestsController.java
- No-auth endpoint to create source request succeeded if a null or
invalid (not belonging to any user) email was provided. Now it will
fail if it cannot resolve a valid user from the provided email or
if an email is not provided at all
- When writing an application check if a revoked application is
getting un-revoked. If so only allow it if the editing user is an
admin
- Refactor several endpoints to ensure the old auth and the new
no-auth endpoints call common code rather than being copy-paste
=> Fix bugs in no-auth admin endpoints

atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java, atlas-processing/src/main/java/org/atlasapi/system/debug/DebugModule.java, atlas-processing/src/main/java/org/atlasapi/system/debug/ScheduleDebugController.java
- moved existing code to debug equivalentSchdedules from ContentDebugController to ScheduleDebugController
=> Added debug endpoint to get schedules from ScheduleStore

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleRequestParser.java
Inject the same now into period parsers
=> Schedule: 'now' based queries could be racy between from/to

atlas-core/src/main/java/org/atlasapi/application/AbstractApplicationStore.java, atlas-core/src/main/java/org/atlasapi/application/Application.java
and can be set by sending application with a flag 'revoked'
=> Keys are revoked by default

atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
- There is a bug with the partitioning logic which means updates on
one particular content ID--which has started getting updated very
frequently recently--ends up on multiple worker threads. These
threads then compete for the same lock and as a result only one
thread can proceed while the others are blocked. This in turns
slows down the worker and causes a backlog. There is a fix for the
partitioning logic being deployed, however for the sanity of
support over the weekend the affected ID will get temporarily banned.
=> Ban content update messages with given resource ID

atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
This reverts commit b71b7fa1385c36d74d7d913c430bc5eb834696ec.
=> Revert "Ban content update messages with given resource ID"

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
- Due to the use of synchronised we are effectively making two
separate workers single threaded even though we have dozens of
threads for each. This is affecting our ability to update
equivalent schedules in a streaming fashion and forcing us to do
scheduled bootstraps to ensure data consistency
- This commit replaces the use of synchronised with a group lock. The
lock is the concatenation of the channelId, source and date for each
schedule day that we are updating.
=> Replace synchronised with locks

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
when provided with  non_merged annotation
=> Schedule returns non merged broadcasts 

atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraph.java
to match the same of copyWithAfferent and avoid future issue
=> fixing bug in copyWithEfferent implementation 

atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java
also needs sub_items_summaries annotation
=> fixing bug when extended_description

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java, atlas-core/src/main/java/org/atlasapi/hashing/HashGenerator.java, atlas-core/src/main/java/org/atlasapi/hashing/HashValueExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/content/ContentHashGenerator.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/CountryExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/EnumExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/Extractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/LocaleExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/NativeExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/PriceExtractor.java, atlas-core/src/main/java/org/atlasapi/hashing/extractors/SourceStatusExtractor.java
- Add class Javadoc
- Add meters to ContentHashGenerator to measure how often we failed
to generate a hash
- Refactor HashValueExtractor to move extraction logic out to
separate classes and methods to improve code readability
=> Incorporate code review comments

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
- We are getting quite a few of these failures. The logging is so we
can capture the failing IDs
=> Add logging for failing to resolve content during bootstrap

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTranslator.java, atlas-elasticsearch/src/main/java/org/atlasapi/content/EsLocation.java, atlas-elasticsearch/src/test/java/org/atlasapi/content/EsLocationTest.java
Gave ESLocation knowledge of aliases so that they can be recognised and searched with an ES query.
=> Mbst 16441/writing aliases

atlas-processing/src/main/java/org/atlasapi/system/ProcessingMetricsModule.java
- Our graphite server does not have UDP enabled
=> Change Graphite reporter to use TCP

atlas-neo4j/src/main/java/org/atlasapi/neo4j/Neo4jModule.java, atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/Neo4jContentStore.java, atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/Neo4JContentStoreTest.java
- Also small refactoring of code to eliminate duplication and to
avoid both logging and throwing an exception
=> Add timers to Neo4jContentStore

atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/HierarchyWriter.java, atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/HierarchyWriterIT.java
- We now only write in the direction episode -> series -> brand only.
This is for performance reasons as we have content like flat brands
with thousands of episodes that is very slow to update if all of
these relationships have to be updated every time
=> Change hierarchy writer to only write relationships in one direction

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTranslator.java
- The business logic behind locations is that a missing start dateTime
implies a location has been available since forever while a missing
end dateTime implies a location is available until forever. Before we
were ignore locations with missing dateTimes which meant an
actionable location call would mistakenly not return the items of
those locations
=> Persist locations with missing availability start/end times to ES

atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreContentUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
- Add metrics to mark reception of message to Neo4j workers
- Enable Kafka consumer metrics for all workers
=> Add metrics to workers

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java, atlas-core/src/main/java/org/atlasapi/hashing/content/ContentHashGenerator.java, atlas-processing/src/main/java/org/atlasapi/messaging/ContentEquivalenceUpdatingWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreGraphUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreScheduleUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/TopicIndexingWorker.java, atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorker.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ScheduleReadWriteWorker.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/SeparatingEventReadWriteWorker.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/TopicReadWriteWorker.java, atlas-processing/src/test/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorkerTest.java, atlas-processing/src/test/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorkerTest.java, atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorkerTest.java, atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/EventReadWriteWorkerTest.java, atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorkerTest.java
Reverts atlasapi/atlas-deer#410
=> Revert "Standardise metric naming"

atlas-processing/pom.xml
- This is to deal with this issue
https://github.com/dropwizard/metrics/issues/694
=> Change metrics to 3.1.2

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java, atlas-testlib/src/main/java/org/atlasapi/schedule/EquivalentScheduleStoreTester.java
- Before we were writing the broadcast ID based on the broadcast ID
contained in the ScheduleUpdate which was delivered via messaging.
However when we resolve the content currently in the DB for that
broadcast we also try to match based on channel ID and transmission
interval. That meant that if we had a broadcast that changed IDs
since the schedule update message was generated we would end up
writing that broadcast with the wrong broadcast ID clustering key.
If that broadcast then became stale we would never be able to
delete it as we would be trying to delete the wrong ID
=> Fix bug where we write a broadcast with the wrong broadcast ID

atlas-cassandra/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java, atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java, atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraEquivalentScheduleStoreIT.java
- This is intended to reduce the number of updates those workers have
to do by accepting that the content and equivalence graph of old
broadcasts may be a bit stale
=> Change content/equivalence updates to not update rows older than 14 days

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleListWriter.java, atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java, atlas-core/src/main/java/org/atlasapi/application/ApplicationAccessRole.java
Reverts atlasapi/atlas-deer#456
=> Revert "Add support for serving schedules from PA & EBS to BT"

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleListWriter.java, atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java, atlas-core/src/main/java/org/atlasapi/application/ApplicationAccessRole.java
Reverts atlasapi/atlas-deer#459
=> Revert "Mbst 17229/support schedules from pa and ebs"

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
The order of the original query is now used to order the channel
schedules when they have all been resolved.
Previously, the order of the resolved channels was used which was
not the same.
=> Fix for Deer not returning channels in query order

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
Reverts atlasapi/atlas-deer#471
=> Revert "Fix for Deer not returning channels in query order"

atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
- We are retaining the blacklist mechanism itself for potential
future need
=> Remove all graphs from blacklist

atlas-api/pom.xml, atlas-api/src/main/java/org/atlasapi/system/MetricsModule.java, atlas-processing/pom.xml, atlas-processing/src/main/java/org/atlasapi/system/ProcessingMetricsModule.java, pom.xml
- Also add JVM metrics to both app and processing servers
=> Enable metrics on Deer app servers

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsLocation.java
Fix incorrect casting of a set to a list.
=> Fix incorrect casting to list

atlas-processing/src/main/java/org/atlasapi/system/debug/DebugModule.java, atlas-processing/src/main/java/org/atlasapi/system/debug/DelphiController.java, atlas-processing/src/main/java/org/atlasapi/system/debug/serializers/AdjacentsSerializer.java, atlas-processing/src/main/java/org/atlasapi/system/debug/serializers/EquivalenceGraphSerializer.java, atlas-processing/src/main/java/org/atlasapi/system/debug/serializers/ResourceRefSerializer.java, atlas-processing/src/main/java/org/atlasapi/system/debug/serializers/package-info.java
- Also rename to /delphi/graph/{id}.json
=> Move delphi /adjacents/{id}.json endpoint to Atlas Deer app servers

atlas-api/src/main/java/org/atlasapi/output/writers/BroadcastWriter.java, atlas-cassandra/src/main/java/org/atlasapi/content/BroadcastSerializer.java, atlas-cassandra/src/main/java/org/atlasapi/content/v2/model/udt/Broadcast.java, atlas-cassandra/src/main/java/org/atlasapi/content/v2/serialization/BroadcastSerialization.java, atlas-cassandra/src/main/protobuf/content.proto, atlas-cassandra/src/test/java/org/atlasapi/content/BroadcastSerializerTest.java, atlas-core/src/main/java/org/atlasapi/content/Broadcast.java, atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/hashing/HashValueExtractorTest.java, atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyContentTransformer.java
Reverts atlasapi/atlas-deer#486
=> Revert "Add revised repeat flag to deer model"

atlas-cassandra/src/main/java/org/atlasapi/content/BroadcastSerializer.java, atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java, atlas-cassandra/src/main/java/org/atlasapi/content/ContentSerializationVisitor.java, atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java, atlas-cassandra/src/main/java/org/atlasapi/schedule/ItemAndBroadcastSerializer.java, atlas-cassandra/src/test/java/org/atlasapi/content/BroadcastSerializerTest.java
- We were setting the revised repeat from the repeat flag instead of
the revised repeat one
=> Fix revised repeat serialisation bug

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java, atlas-cassandra/src/main/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStore.java, atlas-cassandra/src/main/java/org/atlasapi/event/DatastaxCassandraEventStore.java, atlas-cassandra/src/main/java/org/atlasapi/organisation/DatastaxCassandraOrganisationStore.java, atlas-cassandra/src/main/java/org/atlasapi/organisation/OrganisationUriStore.java, atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java, atlas-cassandra/src/main/java/org/atlasapi/schedule/DatastaxCassandraScheduleStore.java, atlas-cassandra/src/main/java/org/atlasapi/segment/CassandraSegmentStore.java
- This is to work around
https://issues.apache.org/jira/browse/CASSANDRA-10786
=> Replace all SELECT * with explicit selects

atlas-cassandra/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java
- This filtering logic currently has a bug (MBST-17731) in that it
removes items it should not. These metrics are intended to give
some visibility into how much extra work Cassandra will have to do
after this is fixed
=> Add metrics around equiv item filter logic

atlas-cassandra/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java, atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraEquivalentScheduleStoreIT.java
- Previously when storing a schedule entry (single broadcast) we:
-- Kept all items for each source in the equiv graph if none of the
broadcasts of these items matched the broadcast of the schedule
entry
-- Kept only one item per source if one such item was found that
matched the broadcast of the schedule entry
- This logic is contrary to what we expect here which is that every
schedule row will have the entire equivalence graph. This commit
fixes this behaviour.
- We are preserving the logic that filters out any non-matching
broadcasts since they are not relevant in the context of the
equivalent schedule store
=> Fix schedule store to not filter items by source

atlas-api/src/main/java/org/atlasapi/AtlasApiModule.java, atlas-api/src/main/java/org/atlasapi/system/SourcesController.java, atlas-api/src/main/java/org/atlasapi/system/SourcesModule.java
* Move sources endpoint to /system/
* Keep functionality of listing all publishers from: `application/SourcesController:325`
=> Relocate sources endpoint

atlas-api/src/main/java/org/atlasapi/AtlasApiModule.java, atlas-api/src/main/java/org/atlasapi/system/SourcesController.java, atlas-api/src/main/java/org/atlasapi/system/SourcesModule.java
Copy sources endpoint from /4/ to /system/
Keep functionality of listing all publishers from: application/SourcesController:325
=> Move sources list endpoint to system

atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraphFilter.java
- This error can happen when the equivalent_content_index as a stale
row that connects a content ID to the wrong graph. That bug is being
investigated, but on the flip-side this aggressive fail-fast is
causing an entire call to fail when only a single ID in that call
would have been problematic. This changes `checkArgument` to a
`log.warn` and reverts the filter's behaviour to be the same as
when no graph has been provided
=> Do not fail-fast on EquivalenceGraphFilter.java construction

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java
We used to have a bug that caused us to only migrate itemRefs and seriesRefs that were already present in C*. Now that we've fixed that, we're migrating all refs we get from Mongo. It turns out that some of those refs don't actually exist in Mongo, because hail Satan. This makes the code move on and try the rest of the refs instead of failing fast.
=> Swallow exceptions for individual itemRefs when migrating content

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java
- Previous code was falsely returning blackout false when the chosen
item had blackout false and the non chosen item had blackout true
=> Fix blackout merging not showing valid blackout

atlas-core/src/main/java/org/atlasapi/output/StrategyBackedEquivalentsMerger.java
The publishers from the equivalents were not included in the explicit list from from the applications reads. These are now appended.
=> fix publisher missing from explicit ordering

atlas-core/src/main/java/org/atlasapi/output/StrategyBackedEquivalentsMerger.java
This functionality has been implemented into the applications service client as it is used across Owl and Deer in multiple places
=> Revert publisher ordering including other publishers

atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/BootstrapModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/DirectAndExplicitEquivalenceMigrator.java, atlas-processing/src/main/java/org/atlasapi/system/debug/DebugModule.java
- Change content bootstrap to use a message sending equiv graph store
so that equivalence changes will generate messages for the equiv
schedule store
=> Change content bootstrap to update equiv schedule store graphs

atlas-cassandra/src/main/java/org/atlasapi/content/v2/CqlContentStore.java
There are a lot of class cast exceptions so gathering some more detailed
information will help locate the source of the issue.
=> Add logging to debug bootstrap workers

atlas-core/src/main/java/org/atlasapi/content/Broadcast.java, atlas-core/src/main/java/org/atlasapi/content/BroadcastAggregator.java, atlas-core/src/test/java/org/atlasapi/content/BroadcastAggregatorTest.java
As continuations were showing up as seperate broadcasts.
=> Merge Continuations in aggrecated broadcasts

atlas-core/src/main/java/org/atlasapi/content/BroadcastAggregator.java
Was throwing an exception when trying to add the same channel to the map
=> handle duplicate channel in map

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java, atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java, atlas-processing/src/test/java/org/atlasapi/system/bootstrap/ContentBootstrapListenerTest.java
Filter the list of images even if there is not top match.
Also fix the bootstrap hierarchy to work with non-episode items.
=> Fix images filtering

atlas-processing/Dockerfile, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
Reverts atlasapi/atlas-deer#560
=> Revert "extract executor config for telescope"

atlas-processing/Dockerfile, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
Reverts atlasapi/atlas-deer#561
=> Revert "Revert "extract executor config for telescope""

atlas-api/src/main/java/org/atlasapi/output/annotation/ChannelGroupMembershipListWriter.java
fix channel group id bug & filter channel groups by application
=> Channel group sorting out

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
For now, that means the lowest ID is used, that ID's source is also
used, and then the same_as (equivalentTo) is fixed up.
=> Fix id/same_as output merging to be consistent.

atlas-api/src/main/java/org/atlasapi/output/OutputContext.java, atlas-api/src/main/java/org/atlasapi/output/annotation/AvailableContentDetailAnnotation.java, atlas-api/src/main/java/org/atlasapi/output/annotation/UpcomingContentDetailAnnotation.java, atlas-api/src/main/java/org/atlasapi/output/writers/ContainerSummaryWriter.java, atlas-api/src/main/java/org/atlasapi/output/writers/SeriesSummaryWriter.java, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/main/java/org/atlasapi/query/common/Query.java, atlas-api/src/main/java/org/atlasapi/query/common/context/QueryContext.java, atlas-api/src/main/java/org/atlasapi/query/v4/content/IndexBackedEquivalentContentQueryExecutor.java, atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java, atlas-api/src/main/java/org/atlasapi/query/v4/topic/TopicContentQueryExecutor.java, atlas-api/src/test/java/org/atlasapi/output/writers/ContainerSummaryWriterTest.java, atlas-api/src/test/java/org/atlasapi/output/writers/SeriesSummaryWriterTest.java, atlas-api/src/test/java/org/atlasapi/query/v4/content/IndexBackedEquivalentContentQueryExecutorTest.java, atlas-api/src/test/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImplTest.java, atlas-api/src/test/java/org/atlasapi/query/v4/topic/TopicContentQueryExecutorTest.java, atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java, atlas-cassandra/src/test/java/org/atlasapi/content/CassandraEquivalentContentStoreRowIT.java, atlas-core/src/main/java/org/atlasapi/content/ContainerSummaryResolver.java, atlas-core/src/main/java/org/atlasapi/content/MergingEquivalentsResolverBackedContainerSummaryResolver.java, atlas-core/src/main/java/org/atlasapi/criteria/attribute/Attributes.java, atlas-core/src/main/java/org/atlasapi/equivalence/AnnotationBasedMergingEquivalentsResolver.java, atlas-core/src/main/java/org/atlasapi/equivalence/EquivalentsResolver.java, atlas-core/src/main/java/org/atlasapi/equivalence/MergingEquivalentsResolver.java, atlas-core/src/test/java/org/atlasapi/content/MergingEquivalentsResolverBackedContainerSummaryResolverTest.java, atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java, atlas-testlib/src/main/java/org/atlasapi/content/EquivalentContentStoreTester.java
when using new request parameter and access role
JIRA ticket https://metabroadcast.atlassian.net/browse/ENG-320
=> Support API reads at a higher consistency level 

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/BootstrapModule.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java, atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
to ContentDebug/ContentBootstrap Controllers
=> Add sendKafkaMessage boolean flag 

atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorker.java, atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/DirectAndExplicitEquivalenceMigrator.java, atlas-processing/src/test/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorkerTest.java, pom.xml
Changes to accommodate LookupEntry restructure.
=> (ENG-741) Asymmetric equivalence

.gitignore, atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/SearchController.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/BeforeAfterAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/ChannelGroupAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/EnumAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/IdAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/RangeAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SearchAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributeList.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributeSingle.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributes.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/TermAttribute.java
Changes affecting https://metabroadcast.atlassian.net/browse/ENG-857.
=> Sherlock Bug Fixes

atlas-api/pom.xml, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/MultiFieldAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/RangeAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SearchAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributes.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockBoolAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockParameter.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockSingleMappingAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockSingleMappingAttributeList.java
Several type changes and some changes to attributes to fit with changed Sherlock types.
=> Update parameters to match Sherlock type changes.

atlas-api/pom.xml, atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/ContentResolvingSearcher.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/SearchController.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/BeforeAfterAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/BetweenRangeAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/BooleanAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/ChannelGroupAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/EnumAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/IdAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/KeywordAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/MultiFieldAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/RangeAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SearchAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributes.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockBoolAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockSingleMappingAttribute.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockSingleMappingAttributeList.java, atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/TermAttribute.java, pom.xml
Staying up to date for some Sherlock class renaming and restructuring.
=> Update naming and paths for Sherlock classes.

atlas-cassandra/src/main/java/org/atlasapi/content/AbstractContentStore.java, atlas-cassandra/src/main/java/org/atlasapi/content/v2/CqlContentStore.java, atlas-cassandra/src/test/java/org/atlasapi/content/CassandraContentStoreIT.java, atlas-core/src/main/java/org/atlasapi/content/Episode.java, pom.xml
=> Parentless episodes

atlas-api/src/main/java/org/atlasapi/www/filter/RequestLoggingFilter.java, atlas-api/src/main/webapp/WEB-INF/web.xml
To aid in investigating response time spikes
=> Log requests
