atlas-core/src/main/java/org/atlasapi/equivalence/ApplicationEquivalentsMerger.java
atlas-core/src/main/java/org/atlasapi/equivalence/DefaultMergingEquivalentsResolver.java
atlas-core/src/main/java/org/atlasapi/output/EquivalentsMergeStrategy.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/main/java/org/atlasapi/output/StrategyBackedEquivalentsMerger.java
atlas-core/src/test/java/org/atlasapi/output/StrategyBackedEquivalentsMergerTest.java

If the requested ID has the same source as the most precedent
piece of content, then requested ID content should be the
merge victim, such that its attributes are taken in preference
to other equivalent content in the set.

Merge victim should take into account requested ID

---

atlas-core/src/main/java/org/atlasapi/application/ApplicationSources.java
atlas-core/src/main/java/org/atlasapi/model/translators/ApplicationModelTranslator.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/main/java/org/atlasapi/util/ImmutableCollectors.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java

Allow precedence ordering for merging of containers'
contents to be specified separately from the overall precedence
ordering.

Separate precedence for hierarchies

---

atlas-api/src/main/java/org/atlasapi/query/QueryModule.java
atlas-core/src/main/java/org/atlasapi/output/EquivalentSetContentHierarchyChooser.java
atlas-core/src/main/java/org/atlasapi/output/FirstHierarchyContentHierarchyChooser.java
atlas-core/src/main/java/org/atlasapi/output/MostPrecidentWithChildrenContentHierarchyChooser.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/test/java/org/atlasapi/output/BroadcastMergingTest.java
atlas-core/src/test/java/org/atlasapi/output/FirstHierarchyContentHierarchyChooserTest.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java

From an equivalent set of containers, choose the first
one that has a true hierarchy (brand/series/episode),
if there is one, in preference to flat (brand/episode)
structure.

Choose container with hiearchy during output merging

---

atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java
atlas-cassandra/src/main/java/org/atlasapi/content/ContentSerializationVisitor.java
atlas-cassandra/src/main/java/org/atlasapi/content/PrioritySerializer.java
atlas-cassandra/src/main/protobuf/common.proto
atlas-cassandra/src/main/protobuf/content.proto
atlas-cassandra/src/test/java/org/atlasapi/content/PrioritySerializerTest.java

Added changes to common.proto and content.proto to have two separate list for Priority score reasons.
Furthermore updated following classes for serialisation and deserialisation:
PrioritySerializer
ContentSerializationVisitor
ContentDeserializationVisitor
Updated tests:
PrioritySerializer

Mbst 13222 adding separate score reasons

---

atlas-elasticsearch/src/main/java/org/atlasapi/util/FiltersBuilder.java

- Current actionable filter will fail to return currently broadcast
content if the broadcastTimeGreaterThan time is the current time.
This will ensure that if a broadcast is even partially in the
requested range it will show up in the query
- Added defensive guard to ensure broadcastTimeGreaterThan is less or
equal to broadcastTimeLessThan if both have been provided

Change ES broadcast range filter to cover broadcasts partially in range

---

atlas-processing/src/main/java/org/atlasapi/messaging/ContentEquivalenceUpdatingWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreScheduleUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/TopicIndexingWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/EventReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ScheduleReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/TopicReadWriteWorker.java

- Log the IDs included in the message to allow seeing when a piece of
content has been processed
- Change all loggers to be static as per code style

Log when a messaging worker is processing message

---

atlas-core/src/main/java/org/atlasapi/util/GroupLock.java
atlas-core/src/test/java/org/atlasapi/util/GroupLockTest.java

This will ensure that locks can only be released by
threads that own them, as well as give us the re-entrant
properties which may avoid deadlocks.

Switch GroupLock to use a ReentrantLock

---

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/BootstrapModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ChannelIntervalScheduleBootstrapTask.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ChannelIntervalScheduleBootstrapTaskFactory.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ScheduleBootstrapController.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ScheduleBootstrapWithContentMigrationTaskFactory.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ScheduleBootstrapper.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java

By adding the migrateContent=true URI parameter to the existing

Allow schedule and all equivalent content to be bootstrapped

---

atlas-api/src/main/java/org/atlasapi/AtlasApiModule.java
atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java
atlas-api/src/main/java/org/atlasapi/MonitoringWebModule.java
atlas-api/src/main/java/org/atlasapi/system/ApiMetricsModule.java
atlas-api/src/main/java/org/atlasapi/system/HealthModule.java
atlas-api/src/main/java/org/atlasapi/system/MetricsModule.java
atlas-processing/src/main/java/org/atlasapi/AtlasProcessingModule.java
atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/ProcessingHealthModule.java
atlas-processing/src/main/java/org/atlasapi/system/ProcessingMetricsModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/health/AstyanaxProbe.java

- Reenable cassandra probe on HealthModule
- Split off MetricsRegistry to MetricsModule
- Delete commented out code from MonitoringWebModule
- Extract AstyanaxProbe to its own class for readability and
separation of concerns. This can't be moved to common-persistence
because we don't have the astyanax driver there

Split off MetricsRegistry to MetricsModule to eliminate circ dep

---

atlas-cassandra/src/main/java/org/atlasapi/CassandraPersistenceModule.java

to avoid creating multiple sessions (and for the glory of the empire).

Cache the Dstax session in C*PersistenceModule

---

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java

We have a tolerance in equivalence, but did not have one for
broadcast merging on output. We will now match broadcasts
between equivalent items if they have a start date within
five minutes of each other.

Merge broadcasts where start times are slightly different

---

atlas-api/src/main/java/org/atlasapi/output/annotation/LocationsAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/writers/time/UnixMillenniumBugFixer.java
atlas-api/src/test/java/org/atlasapi/output/writers/time/UnixMillenniumBugFixerTest.java

- This attempts to fix the Unix Millennium Bug for 32-bit clients by
changing any date time that is greater than 2038-01-01T00:00:00.0 to
that value
- This was needed because some Android devices are 32-bit and we
ingest from content providers that sometimes give us dates in the
year 3000
- This "fix" is set to be disabled automatically on
2016-03-05T08:00:00.0Z and there is a unit test set to fail then to
alert us to remove this

Clamp location availability start/end to deal with Year 2038 bug

---

atlas-cassandra/src/main/java/org/atlasapi/CassandraPersistenceModule.java
atlas-cassandra/src/test/java/org/atlasapi/content/CassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraScheduleStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/util/TestCassandraPersistenceModule.java
atlas-core/src/main/java/org/atlasapi/content/AbstractContentStore.java
atlas-core/src/main/java/org/atlasapi/content/AbstractEquivalentContentStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
atlas-core/src/main/java/org/atlasapi/event/ConcreteEventStore.java
atlas-core/src/main/java/org/atlasapi/schedule/AbstractScheduleStore.java
atlas-core/src/main/java/org/atlasapi/segment/AbstractSegmentStore.java
atlas-core/src/main/java/org/atlasapi/topic/AbstractTopicStore.java
atlas-core/src/test/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStoreTest.java
atlas-core/src/test/java/org/atlasapi/event/ConcreteEventStoreTest.java

- This is intended to ensure messages about the same resource always
go the same partition and that therefore we have ordering guarantees
about those messages. This is irrelevant when it comes to idempotent
messages, but it is required to ensure correctness when it comes to
non-idempotent ones like EquivalenceGraphUpdateMessage

Change users of MessageSender to specify partition key

---

atlas-elasticsearch/pom.xml
atlas-elasticsearch/src/main/java/org/atlasapi/ElasticSearchContentIndexModule.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndex.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsContentSearcherV3CompatibilityTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsContentTitleSearcherTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexingTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/PseudoEquivalentContentIndexIT.java
atlas-elasticsearch/src/test/java/org/atlasapi/topic/EsPopularTopicsIndexTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/util/ElasticSearchHelper.java

- Currently due to an issue we can't inline groovy scripts to
requests made to the production cluster so we have to operate in two
modes. We inline the script for integration tests and reference a
script saved on the servers for production
- When ordering is requested and there is no fuzzy search which
requires score sorting we will also sort according to publisher
precedence to ensure that when deduping we are more likely to sort
according the value that will be displayed to the user

Sort ES hits according to publisher precedence using groovy script

---

atlas-core/src/main/java/org/atlasapi/content/IndexQueryResult.java
atlas-core/src/test/java/org/atlasapi/content/IndexQueryResultTest.java
atlas-elasticsearch/src/main/java/org/atlasapi/ElasticSearchContentIndexModule.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/DelegateContentIndex.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/DelegateIndexQueryResult.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndex.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/PseudoEquivalentContentIndex.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/DelegateIndexQueryResultTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/PseudoEquivalentContentIndexIT.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/PseudoEquivalentContentIndexTest.java

- Currently we grab the ID we see out of every equivalent set. This
creates the problem that after merging on output we might show
different values on the API than the ones used for ordering by ES
thus the ordering will appear wrong. This is intended to fix that
- Change IndexQueryResult to only store IDs and create separate
DelegateIndexQueryResult to store additional information required by
the PseudoEquivalentContentIndex (namely canonicalID and publisher) to
avoid leaking that information to other parts of the code that don't
need them and making those interfaces more confusing. The interface
DelegateContentIndex has been created to handle communication between
the PseudoEquivalentContentIndex and EsUnequivalentContentIndex
- Have PseudoEquivalentContentIndex return the normal ID of …

Change ES deduping to take duplicate with highest precedence publisher

---

atlas-legacy/src/main/java/org/atlasapi/system/legacy/BaseLegacyResourceTransformer.java

- Drop images with null canonical URI when transforming legacy images
to the Deer model

Fix NPE when transforming legacy images with null canonical URI

---

atlas-elasticsearch/src/main/java/org/atlasapi/util/FiltersBuilder.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsUnequivalentContentIndexTest.java

- Split failing actionable content filter test into multiple tests
that each cover a single scenario to assess which scenario is failing
- Fix actionable filter bug where no region ID has been provided. In
that scenario the filters were written in the wrong order (nesting
outside the or filter rather than the other way around)

Fix bug in actionable content filter

---

atlas-api/src/main/java/org/atlasapi/query/QueryModule.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java
atlas-core/src/main/java/org/atlasapi/equivalence/AnnotationBasedMergingEquivalentsResolver.java

The Data Comparison Service needs to be able to see unequivalated output, so that each data source's data can be rendered and compared by a user.

added annotation to return non-merged content

---

atlas-cassandra/pom.xml
pom.xml

This should reduce GC churn from various `byte[]` allocations in the C* driver.
Tested on `stage`, basic heap profiling says it's good at getting rid of the crazy amounts of `byte[]` allocations we have, and GC gets a bit better. As far as I can tell, there are no downsides.

Use EPoll transport for Netty.

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-testlib/src/main/java/org/atlasapi/schedule/EquivalentScheduleStoreTester.java

In the case where a broadcast ID is used on mulitple broadcasts
across two days, and one is removed, if the update interval of
the schedule spans both days, then all broadcasts with that
ID were removed.
We now only remove broadcasts on the calendar day in which the
stale broadcast is. There remains an edge case if both the valid
and invalid broadcast are on the same day.

Be less eager to remove stale broadcasts

---

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTranslator.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/EsUnequivalentContentIndexer.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/EsContentTranslatorTest.java
atlas-elasticsearch/src/test/java/org/atlasapi/content/PseudoEquivalentContentIndexIT.java

- Change denormalisation logic to check if a broadcast is actively
published before denormalising it
- Change denormalisation logic to remove existing broadcasts from
parent series that have the same channel ID and start/end
transmission times as item broadcasts before merging them with the
item broadcasts. This is to effectively remove broadcasts belonging
to this item if they are no longer actively published
- Move logic to get possible parent series from ES and to reindex a
series on ES out of the EsContentTranslator and into
EsUnequivalentContentIndexer to improve separation of concerns and to
make testing easier
- Change parsing of ES broadcast channel ID to expect long since IDs
are longs
- Fix Failing test in PseudoEquivalentContentIndexIT

Remove non actively published broadcasts when denormalising on ES series

---

atlas-api/src/main/java/org/atlasapi/query/v4/search/SearchController.java
atlas-core/src/main/java/org/atlasapi/application/users/User.java
atlas-core/src/main/java/org/atlasapi/content/Actor.java
atlas-core/src/main/java/org/atlasapi/content/KeyPhrase.java
atlas-core/src/main/java/org/atlasapi/schedule/ChannelSchedule.java
atlas-core/src/main/java/org/atlasapi/schedule/ScheduleRef.java
atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTranslator.java

- SearchController: withCurrentBroadcastsOnly expects a primitive
boolean. Passing null with throw a RuntimeException. Change to
passing false instead if not specified
- User: manages method was checking applicationIds contains itself
rather than the provided applicationId. This code is currently unused
- Actor: Fix inconsistent equals/hashCode and change equals to follow
usual patterns rather than doing an instanceof to a specific type
that breaks symmetry of equals with superclass' equals
- KeyPhrase: String.format was expecting 3 parameters, but only two
are passed
- ChannelSchedule: Remove misleading final on a static field; Fix
inconsistent equals/hashCode and non-standard equals as before
- ScheduleRef: Fix inconsistent equals/hashCode and non-standard equals
as before
- …

Fix scariest and some scary FindBugs bugs

---

atlas-api/src/main/java/org/atlasapi/query/v4/channel/ChannelController.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupController.java
atlas-api/src/main/java/org/atlasapi/query/v4/content/ContentController.java
atlas-api/src/main/java/org/atlasapi/query/v4/event/EventController.java
atlas-api/src/main/java/org/atlasapi/query/v4/meta/endpoint/EndpointController.java
atlas-api/src/main/java/org/atlasapi/query/v4/meta/model/ModelController.java
atlas-api/src/main/java/org/atlasapi/query/v4/organisation/OrganisationController.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleController.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleIndexDebugController.java
atlas-api/src/main/java/org/atlasapi/query/v4/search/SearchController.java
atlas-api/src/main/java/org/atlasapi/query/v4/topic/PopularTopicController.java
atlas-api/src/main/java/org/atlasapi/query/v4/topic/TopicContentController.java
atlas-api/src/main/java/org/atlasapi/query/v4/topic/TopicController.java

in case of broken path rather than 500 from ResponseWriterFactory.
Changed wildcard matcher to alpha extension matcher:
i.e.
`schedules.*` to `schedules\\.[a-z]+`
so match schedules.xml & schedules.json, but not schedules.hk45.json

MBST-14517: Tighten RequestPath in * Controllers so return 404 

---

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ChannelIntervalScheduleBootstrapTask.java

- ItemAndBroadcast null checks the passed in Item so there is no
point continuing with this broadcast if we can't resolve a valid Item

Fix NPE in ChannelIntervalScheduleBootstrapTask

---

atlas-core/src/main/java/org/atlasapi/content/AbstractEquivalentContentStore.java
atlas-core/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java
atlas-core/src/main/java/org/atlasapi/schedule/EquivalentScheduleWriter.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalenceGraphUpdateResolver.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ChannelIntervalScheduleBootstrapTask.java
atlas-processing/src/test/java/org/atlasapi/messaging/EquivalenceGraphUpdateResolverTest.java
atlas-processing/src/test/resources/log4j.properties
atlas-testlib/src/main/java/org/atlasapi/schedule/EquivalentScheduleStoreTester.java

- As it is right now equivalence update messages are fat messages that
contain the equivalent sets that have been updated. This means if
we have a queue that is backlogged for several hours, when those
messages do get processed they may temporarily reset the updated
stores to an out-of-date view of the equivalence graphs. This could
potentially undo manual bootstraps that might have been applied to
mitigate the backlog
- Create delegate EquivalenceGraphUpdateResolver that resolves the
current state of the graphs references by the graph update message
and change EquivalentContentIndexingGraphWorker and
EquivalentScheduleStoreGraphUpdateWorker to use the new delegate to
get an up-to-date view of the graphs before passing them to the
downstream stores
- The respective equivalent content …

Make equivalence updates for the equiv schedule and the index idempotent

---

atlas-api/src/main/java/org/atlasapi/output/annotation/LocationsAnnotation.java

We've started handling revocations for availabilities in Nitro, which means we now use the `available`
flag on `Location`s. This makes the API output respect that flag.

Filter unavailable `Location`s from API output.

---

atlas-cassandra/src/main/java/org/atlasapi/content/CrewMemberSerializer.java
atlas-cassandra/src/test/java/org/atlasapi/content/CrewMemberSerializerTest.java

CrewMembers have a bunch of optional fields.
These are serialised without problems, but the deserialiser assumes presence of everything.
Owl only sparsely populates CrewMembers in most cases

MBST-15466: Fix C* CrewMember asymmetric serialisation bug

---

atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java

- Workers where it is not safe to replay messages out of order are set
to only persist failed messages. The others will attempt to retry
persisted failed messages before giving up permanently.

Enable persistent retry policy / failed message persistence on workers

---

atlas-api/src/main/java/org/atlasapi/application/ApplicationsController.java

- We querying for the modified application we were only passing in
the user accounts that had a new application created against them.
If the application was edited instead of created that list would
have been empty so when we try to resolve that application after
updating it we would get a 403 since no user could be found with
permision to access it

Fix bug with POST /application throwing a 403

---

atlas-api/src/main/java/org/atlasapi/output/annotation/ExtendedDescriptionAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/annotation/PriorityScoreReasonsAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/writers/PriorityReasonsWriter.java
atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java

This has been done so that we output priority reasons once the annotation has been provided.

Adding priority_reasons annotation

---

atlas-legacy/src/main/java/org/atlasapi/system/legacy/PaTagMap.java
atlas-legacy/src/test/java/org/atlasapi/system/legacy/PaTagMapTest.java

* tests showed typo in original PA tag mapper
* items with no genres are tagged with "unclassified" this allows us to eliminate them from genre bootstrap activities and perform genre improvement queries

MBST-15351: TopicGenres: add tests, bug fix action films and tag empty genre items

---

atlas-core/src/main/java/org/atlasapi/content/Content.java
atlas-core/src/main/java/org/atlasapi/content/Item.java
atlas-core/src/main/java/org/atlasapi/content/Series.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java
atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
atlas-processing/src/test/java/org/atlasapi/system/bootstrap/ContentBootstrapListenerTest.java

- The bootstrap process is fairly deeply nested. As a result the code
that was recording success/failure messages for each step of the
process ended up being very convoluted and hard to follow. Replace
all that code with a graph that allows parts of the process to
push/pop arbitrary paths in the graph and add success/failure
messages under those paths.

Simplify result reporting in ContentBootstrapListener

---

atlas-cassandra/src/main/java/org/atlasapi/CassandraPersistenceModule.java
atlas-cassandra/src/main/java/org/atlasapi/content/AstyanaxCassandraContentStore.java
atlas-cassandra/src/main/java/org/atlasapi/content/DatastaxCassandraContentStore.java
atlas-cassandra/src/test/java/org/atlasapi/content/AstyanaxCassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/content/CassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/content/DatastaxCassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraScheduleStoreIT.java
atlas-core/src/main/java/org/atlasapi/content/AbstractContentStore.java

- Workers downstream of the content store operate on the entire
equivalence set for each updated content at once. Changing the
partition key to the set ID ensures that all messages of the same
set are always processed by the same worker.
- This is motivated by an issue where multiple updates on different
content belonging to the same equiv set could result in many/all
downstream workers processing the same equiv set at the same time
and therefore competing for the same locks. This would then slow
processing down and cause a backlog.

Change partition key for update content messages to equiv set ID

---

atlas-api/src/main/java/org/atlasapi/application/ApplicationsController.java
atlas-core/src/main/java/org/atlasapi/application/ApplicationAccessRole.java
atlas-core/src/main/java/org/atlasapi/application/ApplicationSources.java
atlas-core/src/main/java/org/atlasapi/model/translators/ApplicationModelTranslator.java

- The existing code was losing the existing access roles every time
an application was updated. This was because Deer duplicates the
application model and its version of the model did not have the
access roles field so it was always empty.

Do not allow modifying of application access roles via the API

---

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java
atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java
atlas-cassandra/src/main/java/org/atlasapi/content/ContentSerializer.java
atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-cassandra/src/test/java/org/atlasapi/content/ContentSerializerTest.java
atlas-core/src/main/java/org/atlasapi/content/Container.java
atlas-core/src/main/java/org/atlasapi/content/Content.java
atlas-core/src/main/java/org/atlasapi/content/Item.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java

-Added new deserialize method that accepts annotations that it can use after
-When deserializing check passed annotation when deserializing broadcasts, locations and sub_items
-Added new test to deserializing

Annotations access moved closer to persistence

---

atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
atlas-processing/src/test/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorkerTest.java

- Not all equivalence graph changes in Owl will generate a Kafka
message therefore if we only update according to what is in the
message we will miss some adjacents
- Also resolving the adjacents as it arrives means we are more
resilient to getting backlogged and less vulnerable to missing
individual messages as we will always write the most up-to-date
view of the equivalence graph with respect to the subject resourceRef

Change Neo4j graph worker to get adjacents from LookupStore

---

atlas-neo4j/src/main/java/org/atlasapi/neo4j/Neo4jModule.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/Neo4jContentStore.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/Neo4JContentStoreTest.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/Neo4jContentStoreIT.java

- This query is quite expensive for Neo4j even if the index and
constraint already exist

Remove logic that generates Neo4j indices on boot

---

atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v4/channel/ChannelWriter.java

Currently this call is very expensive when used with the 'channel_groups_summary' annotation.
It returns all channels belonging to each returned channel group and also for each channel, every channel group that it belongs to.
This change removes the writing of the last part when the /channel_group/ endpoint is called.
The previous behaviour has been retained for the /channel/ endpoint.

Change channel_group endpoint to not show channel groups of channels

---

atlas-api/src/main/java/org/atlasapi/output/writers/BroadcastWriter.java

A class was not changed for new ChannelWriter constructor. It has now been fixed to use the new version.

Fix for new constructor syntax

---

atlas-neo4j/src/main/java/org/atlasapi/neo4j/Neo4jModule.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/Neo4jContentStore.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/BroadcastWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/ContentWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/EquivalenceWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/HierarchyWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/LocationWriter.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/Neo4JContentStoreTest.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/resolvers/EquivalentSetResolverIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/BroadcastWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/ContentWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/EquivalenceWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/HierarchyWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/LocationWriterIT.java

- Add metrics to every part of the Neo4jContentStore write pipelines
to identify the bottleneck
- Move metric definition in the Neo4jContentStore constructor to
simplify its builder
- Remove the metrics from the individual writers since they were not
helpful in finding any bottleneck (individually they all appear to
be fast)

Improve Neo4jContentStore metrics

---

atlas-core/src/main/java/org/atlasapi/entity/Id.java
atlas-core/src/main/java/org/atlasapi/entity/ResourceRef.java
atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraph.java
atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraphUpdateMessage.java
atlas-core/src/main/java/org/atlasapi/messaging/EquivalenceAssertionMessage.java
atlas-core/src/main/java/org/atlasapi/messaging/EquivalentContentUpdatedMessage.java
atlas-core/src/main/java/org/atlasapi/messaging/JacksonMessageSerializer.java
atlas-core/src/main/java/org/atlasapi/messaging/ResourceUpdatedMessage.java
atlas-core/src/main/java/org/atlasapi/schedule/ScheduleUpdateMessage.java
atlas-core/src/test/java/org/atlasapi/equivalence/EquivalenceGraphUpdateMessageTest.java
atlas-core/src/test/java/org/atlasapi/schedule/ScheduleUpdateMessageTest.java
atlas-processing/pom.xml
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ColumbusTelescopeReporter.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorkerTest.java
atlas-processing/src/test/java/org/atlasapi/system/debug/EventDebugControllerTest.java
pom.xml

This has been done so that we know more about content migration.
Updating the Jackson version to 2.8
Adding annotations to Id class so that we can get id as long and Long. Updated common dependency to the new version 2 as Timestamp millis method now also have Jackson annotations that we need in the deserialization logic.
Fixing failing tests as the deserialization logic for Joda intervals has changed and when deserializing interval, it's automatically converted to UTC.

Adding reporting to Columbus Telescope for content migration

---

atlas-neo4j/src/main/java/org/atlasapi/neo4j/Neo4jModule.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/Neo4jContentStore.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/ContentWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/EquivalenceWriter.java
atlas-neo4j/src/main/java/org/atlasapi/neo4j/service/writers/HierarchyWriter.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/Neo4JContentStoreTest.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/ContentWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/EquivalenceWriterIT.java
atlas-neo4j/src/test/java/org/atlasapi/neo4j/service/writers/HierarchyWriterIT.java

- Change EquivalenceWriter writes to create resourceRef nodes where
needed rather than executing a separate query to write them before
writing equivalence assertions
- Change HierarchyWriter writes to create contentRef nodes where
needed rather than delegating to ContentWriter to create them
- Use ON CREATE SET clauses in ContentWriter to avoid repeatedly
updating data that cannot change
- Remove unnecessary metrics from Neo4jContentStore. The Neo4j driver
does most of the work when the transaction is closed so that is where
most of the execution time is concentrated. The metrics of the
other execution steps are showing unrealistic low values that are
not useful
- Remove methods to write contentRef and resourceRef from
ContentWriter as they are no longer needed

Optimise Neo4j writes to reduce number of updates needed

---

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java
atlas-core/src/main/java/org/atlasapi/hashing/content/ContentHashGenerator.java
atlas-processing/src/main/java/org/atlasapi/messaging/ContentEquivalenceUpdatingWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreScheduleUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/TopicIndexingWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/WorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ScheduleReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/SeparatingEventReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/TopicReadWriteWorker.java
atlas-processing/src/test/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorkerTest.java
atlas-processing/src/test/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorkerTest.java
atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorkerTest.java
atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/EventReadWriteWorkerTest.java
atlas-processing/src/test/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorkerTest.java

- Standardise metric naming across Kafka workers and in
ContentHashGenerator for consistency and to make it easier to
create standardised views for them in Grafana

Standardise metric naming

---

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java

- The graph column in Cassandra is static so for every row of a given
partition key (setId) there is only one graph
- There is no documentation for the reason behind the
`row.getBytes(GRAPH_KEY) != null` check so I'm assuming it's to
cope with old data that hasn't been updated recently and am
therefore preserving the existing logic that copes with the absence
of a graph

Avoid deserialising the same graph more than once

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java

- When a stale broadcast's interval is crossing midnight that
broadcast is stored on both days. When we were deleting that
broadcast we only deleted it from the first day thus creating an
overlap. This change will delete it from both days.

Fix bug where we are not deleting stale broadcasts across midnight

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-testlib/src/main/java/org/atlasapi/schedule/EquivalentScheduleStoreTester.java

- Only delete stale broadcasts from the intersection of the days in
the broadcast interval and the schedule update interval. This way
we will only delete a stale broadcast from a particular day if that
stale broadcast's interval overlaps with that day and and schedule
update we are currently processing also overlaps with that day.
This protects from over-eagerly deleting a broadcast from a day
that the update is not asserting on

Change how stale broadcast deletions are handled

---

atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupChannelWriter.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java

The logic skipped over channel groups summary resolution if the
channels annotation wasnt present. This has now been fixed to
work as intended.

Fix bug causing channel groups summary to not be resolved

---

atlas-api/src/main/java/org/atlasapi/query/v4/channel/ChannelQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java

This stop all ChannelGroups from being returned that do not have a whitelisted ID or Alias namespace. The whitelist was created from the docs page displaying the special BT channel group ID's and namespaces.

Bt annotation fix

---

atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java

The desired effect was there which was removing channel groups
that were not needed however there was no performance gain as
all the channel groups still had to be resolved so we could
check their aliases. A list from the db has been hardcoded so now
we can filter before the ID's are passed to the resolver.

Hardcoded list of ID's to filter by before resolution

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-testlib/src/main/java/org/atlasapi/schedule/EquivalentScheduleStoreTester.java

- As it were we only used the broadcast source ID to determine if a
broadcast was stale or not. This meant that if we had two
broadcasts
-- with the same sourceId
-- in adjacent days
-- that are both in the update interval
-- where one broadcast is stale and the other is not
Because the second broadcast is not stale we assumed that that
particular sourceId is not stale and did not delete either broadcast.
- This code fixes this by checking for staleness per day rather than
across the entire update interval.
- We have also stopped using the stale broadcasts contained in the
message because there is no way to fix them to avoid this bug.
Given we resolve the existing schedule while processing the message
we can determine which broadcasts are stale without needing the
stale broadcasts …

Fix bug when deleting stale broadcasts

---

atlas-cassandra/src/main/java/org/atlasapi/content/AbstractEquivalentContentStore.java
atlas-cassandra/src/main/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStore.java
atlas-cassandra/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java
atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
atlas-core/src/main/java/org/atlasapi/locks/GroupLock.java
atlas-core/src/test/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStoreTest.java
atlas-core/src/test/java/org/atlasapi/util/GroupLockTest.java

Duplicate GroupLock from atlas model with same package name
was causing the class loader to not know which one to pick
meaning it selected the wrong one.
Package names have now been distinctly named.

Fix Group Lock class loader

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraEquivalentScheduleStoreIT.java

- Stales are calculated using the message schedule ref rather than
the broadcasts we have resolved from the content store which are
what will be written. This fix ensures that we are using the
broadcastRefs that will be written when computing stale broadcasts
- This was causing bugs when the broadcast ID had changed between the
time the schedule update message was generated and the time the
message was processed and it resulted in stale broadcasts being
mishandled

Fix bug in how we calculate stale broadcasts

---

atlas-cassandra/src/main/java/org/atlasapi/schedule/AbstractEquivalentScheduleStore.java
atlas-cassandra/src/main/java/org/atlasapi/schedule/CassandraEquivalentScheduleStore.java
atlas-cassandra/src/test/java/org/atlasapi/schedule/CassandraEquivalentScheduleStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/util/TestCassandraPersistenceModule.java

- Equivalence updates should only change the content in a given
broadcast row, but never the schedule itself. This is done by
-- not writing the broadcast when updating equivalences
-- not resolving equiv schedule rows with null broadcasts
-- resolving equiv schedule rows with null broadcasts as
potentially stale when updating the schedule

Change schedule equiv updates to not update the schedule

---

atlas-processing/src/main/java/org/atlasapi/messaging/ContentEquivalenceUpdatingWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingContentWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentIndexingGraphWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreScheduleUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/Neo4jContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/TopicIndexingWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/OrganisationBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ScheduleReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/SeparatingEventReadWriteWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/TopicReadWriteWorker.java

- These measure the time between the moment the message was generated
and the time it finished processing

Add metrics to record the latency of Deer workers

---

atlas-cassandra/src/test/java/org/atlasapi/content/AstyanaxCassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/content/CassandraContentStoreIT.java
atlas-cassandra/src/test/java/org/atlasapi/content/v2/CqlContentStoreIT.java

- Currently this behaviour is broken in the
AstyanaxCassandraContentStore (neither the containerRef not the
containerSummary are being removed) and partially broken in the
CqlContentStore (only the containerRef is being removed). There is
a bug raised for addressing the CqlContentStore issue. The
AstyanaxCassandraContentStore is due for decommission so this will
only be fixed on the new version.

Add test that we can remove a content's container and container summary

---

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleListWriter.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java
atlas-core/src/main/java/org/atlasapi/application/ApplicationAccessRole.java

* Application access role added to determine whether functionality is
needed for the requesting application
* "source" field added to schedule output for channels to show where
the source of the channel data
* Application access role checking in the executor resolves channels from
EBS if that is the applications preferred source

Add support for serving schedules from PA & EBS to BT

---

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleListWriter.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java
atlas-core/src/main/java/org/atlasapi/application/ApplicationAccessRole.java

* Application access role added to determine whether functionality is
needed for the requesting application
* "source" field added to schedule output for channels to show where
the source of the channel data
* Application access role checking in the executor resolves channels from
EBS if that is the applications preferred source

Mbst 17229/support schedules from pa and ebs

---

atlas-cassandra/src/main/java/org/atlasapi/equivalence/CassandraEquivalenceGraphStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
atlas-core/src/test/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStoreTest.java

- The blacklist contains a list of graphs to be blocked and is
updated with all the nodes in that graph every time it is
encountered. Over time it should grow to contain all IDs in a
snapshot of the given graphs

Add dynamically generated graph blacklist

---

atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleListWriter.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleQueryExecutorImpl.java
atlas-core/src/main/java/org/atlasapi/schedule/ChannelSchedule.java

* Moved logic to correct executor - EquivalentScheduleQueryExecutor
* Reverted old executor back to pre-feature state - ScheduleQueryExecutorImpl
* Added schedule source to ChannelSchedule
* Fixed schedule fallback bug if EBS schedule fails to be resolved

Move multiple schedule logic to correct executor

---

atlas-api/src/main/java/org/atlasapi/system/SourcesModule.java
atlas-api/src/main/java/org/atlasapi/system/SystemSourcesController.java

The writer that was being used by /system/sources.json endpoint did not match the one used in  /4/admin/sources.json

use source writer with ID's

---

atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java

- These were using gson contrary to everything else we have and it
was not configured to handle Guava optionals so those weren't printed
correctly

Change content debug endpoints to use Jackson

---

atlas-processing/src/main/java/org/atlasapi/messaging/ContentEquivalenceUpdatingWorker.java

- This is temporary to deal with Owl sending a high volume of updates
on this source due to a bug, MBST-18102

Reject equiv changes on PA summaries

---

atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraphRejectionFilter.java
atlas-core/src/test/java/org/atlasapi/equivalence/EquivalenceGraphRejectionFilterTest.java

- These graphs are the result of bugs in equivalence and they cause
significant problems in the downstream equivalent content and
schedule stores. This prevents these graphs from being generated in
Deer and also adds monitoring so we can have visibility when this
happens

Add filter to reject updates that would result in very large graphs

---

atlas-api/src/main/java/org/atlasapi/output/annotation/ReviewsAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/writers/ReviewsWriter.java
atlas-api/src/test/java/org/atlasapi/output/annotation/ReviewsAnnotationTest.java

If content was removed from the feed, it will not have a source
as that field is now passed through from the ingester rather than
being populated in Deer. This defaults the publisher to match the
content publisher in the case where it is absent.

Fix missing publisher on some RT reviews

---

atlas-core/src/main/java/org/atlasapi/content/BroadcastAggregator.java
atlas-core/src/test/java/org/atlasapi/content/BroadcastAggregatorTest.java

Previously, channels not on the platform were being included in the
excluded variants list which was undesired behaviour. Now, only channels
that are on the platform will be included in the excluded variant list of the parent.

Filter channels not on platform when provided

---

atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapController.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java

Missing the content resolver was causing failures to migrate as
part of the process is resolving the content from owl to call migrates
on children of the currently migrating item.

Add legacy content resolver to bootstrap controller

---

atlas-api/src/main/java/org/atlasapi/query/v4/channel/ChannelQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java

Channels were indirectly part of channel groups from different environments as
the base channels were a member in multiple channel groups ingested from separate
sources. EG. channel A is part of group X in one env and X,Y in another. Y was being
shown when the application only had read access on X

Filter out channel groups the application does not have read access to

---

atlas-processing/Dockerfile
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java

Thread pool is reaching its limit and throwing runtime exceptions rejecting items from the queue. Config has been extracted for easier tuning.
Also removed known usages of deprecated telescope constructor.

extract executor config for telescope

---

atlas-cassandra/src/main/java/org/atlasapi/content/ContentSerializationVisitor.java

Trying to serialize a brand that contains an ItemSummary without a title cases throws
an exception which interrupts the update of the Brand. This change is intended to log
the offending ItemSummary ID and allow the process to continue without it.

Filter item summaries

---

atlas-core/src/main/java/org/atlasapi/content/Described.java
atlas-core/src/main/java/org/atlasapi/entity/Identified.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java

Barb overrides were copying all their nulls over to a less precedenced equiv item before the merging logic had a chance to decide what fields should go where. This still copies over the data but prefers non null fields during the process

Merging bug

---

atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyContentResolver.java
atlas-processing/src/main/java/org/atlasapi/system/debug/ContentDebugController.java
atlas-processing/src/test/java/org/atlasapi/system/debug/ContentDebugControllerTest.java

This is so that the txlog generator, which only has uris at its
disposal, can make a best effort to migrate stuff if needed.
This is also for our convenience.

allow migration of content via uri

---

atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutor.java
atlas-api/src/test/java/org/atlasapi/query/v4/schedule/EquivalentScheduleQueryExecutorTest.java
atlas-cassandra/src/main/java/org/atlasapi/content/ContentDeserializationVisitor.java
atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java
atlas-core/src/main/java/org/atlasapi/equivalence/AnnotationBasedMergingEquivalentsResolver.java
atlas-core/src/main/java/org/atlasapi/equivalence/ApplicationEquivalentsMerger.java
atlas-core/src/main/java/org/atlasapi/output/EquivalentsMergeStrategy.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/main/java/org/atlasapi/output/StrategyBackedEquivalentsMerger.java
atlas-core/src/test/java/org/atlasapi/output/BroadcastMergingTest.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java
atlas-core/src/test/java/org/atlasapi/output/StrategyBackedEquivalentsMergerTest.java

Add annotations with more relaxed filters. Purpose is to fix issue where we only show broadcasts from highest-precedence source in cases where it has only very old broadcasts, while there are lower-precedence sources with more recent (including upcoming) broadcasts.
https://metabroadcast.atlassian.net/browse/ENG-302

Add all broadcasts annotation

---

atlas-elasticsearch/src/main/java/org/atlasapi/content/EsContentTitleSearcher.java

TopChildrenQuery is deprecated and in some sense broken, as it is causes an ArrayIndexOutOfBoundsException on certain queries, amounting to around 20,000 errors per day. ElasticSearch documentation recommends using HasChildQuery instead, which works in a similar way, but should prevent this problem from occurring.

ENG-629 - Changing deprecated TopChildrenQuery to HasChildQuery in ElasticSearch

---

atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentContentStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreGraphUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/messaging/EquivalentScheduleStoreScheduleUpdateWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/BootstrapWorkersModule.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ContentBootstrapWorker.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/ScheduleReadWriteWorker.java
atlas-processing/src/test/java/org/atlasapi/messaging/EquivalentScheduleStoreContentUpdateWorkerTest.java

Also enable schedule migration of YouView related publishers to test latencies for possible switch of PA to YouView schedule data for BT.

Publisher specific metrics

---

atlas-api/src/main/java/org/atlasapi/output/annotation/ContentDescriptionAnnotation.java

When you queried Deer for a piece of content, the `year` field was not visible if the content type was item. This change makes that field visible. (ENG-683)

Show years on items in Deer, not just episodes/films

---

atlas-cassandra/src/main/java/org/atlasapi/content/CassandraEquivalentContentStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraphFilter.java

EquivalenceGraphFilter was causing NullPointerException when trying to get the value of an equivalence graph, added null check for this.
Also added null check for calculating unsafe bytes method.

Fix null pointer future

---

atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/common/validation/AbstractRequestParameterValidator.java
atlas-api/src/main/java/org/atlasapi/query/common/validation/QueryRequestParameterValidator.java
atlas-api/src/main/java/org/atlasapi/query/common/validation/SetBasedRequestParameterValidator.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/ScheduleRequestParser.java
atlas-core/src/main/java/org/atlasapi/criteria/attribute/Attributes.java

The query parameter is added for all endpoints and is simply named 't', and can be used to bypass any caching when required.

Add cache bypass query parameter

---

atlas-core/src/main/java/org/atlasapi/content/Brand.java
atlas-core/src/main/java/org/atlasapi/content/Clip.java
atlas-core/src/main/java/org/atlasapi/content/Container.java
atlas-core/src/main/java/org/atlasapi/content/ContentGroup.java
atlas-core/src/main/java/org/atlasapi/content/Described.java
atlas-core/src/main/java/org/atlasapi/content/Episode.java
atlas-core/src/main/java/org/atlasapi/content/Film.java
atlas-core/src/main/java/org/atlasapi/content/Item.java
atlas-core/src/main/java/org/atlasapi/content/Player.java
atlas-core/src/main/java/org/atlasapi/content/Series.java
atlas-core/src/main/java/org/atlasapi/content/Service.java
atlas-core/src/main/java/org/atlasapi/content/Song.java
atlas-core/src/main/java/org/atlasapi/entity/Person.java
atlas-core/src/main/java/org/atlasapi/output/EquivalentsMergeStrategy.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/main/java/org/atlasapi/output/StrategyBackedEquivalentsMerger.java
atlas-core/src/main/java/org/atlasapi/segment/Segment.java
atlas-core/src/main/java/org/atlasapi/topic/Topic.java
atlas-core/src/test/java/org/atlasapi/output/BroadcastMergingTest.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java
atlas-core/src/test/java/org/atlasapi/output/StrategyBackedEquivalentsMergerTest.java

See ticket for full context, but basically merging doesn't work well for every field if lowest ID is not from highest precedence source. This is due to some hacky code which tampered with an existing piece of context from the equivset to create the merged content. 
This rework instead aims to create a new piece of content from scratch to represent the merged content, while maintaining all existing requirements and constraints.
https://metabroadcast.atlassian.net/browse/ENG-820

Rework merging pipeline: eng-820

---

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java

This adds merging logic for languages & certificates
to all content types (previously, it was just films). 
This fixes cases such as editors renaming a brand, 
which adds a higher precedence source content
with no language the equiv set, resulting in no
language being visible in Shaman. See ENG-813.

Fix merging logic for languages & certificates

---

atlas-api/src/main/java/org/atlasapi/output/JsonResponseWriter.java

since it was being deserialized as something else (some ISO- standard).

Set UTF-8 character encoding header for json responses 

---

atlas-api/src/main/java/org/atlasapi/query/QueryModule.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v5/search/ContentResolvingSearcher.java

Sherlock now uses decoded ids for its documents, so this prevents an error that was occuring where the decoding step in the ContentResolvingSearcher was finding illegal characters in the id string (because they were already decoded). Also moved the idCodec back to QueryWebModule where it was before adding Sherlock to deer, as there is no longer any use for it in the QueryModule.

Remove decoding step in resolving content from Sherlock.

---

atlas-api/src/main/java/org/atlasapi/output/annotation/ContainerSummaryAnnotation.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/test/java/org/atlasapi/output/AnnotationRegistryTest.java

The container field was otherwise not being written at all for series
when using the brand_summary annotation, even if other valid annotations
for the field were used.

Use brand ref writer to write container field for series in api

---

atlas-api/src/main/java/org/atlasapi/elasticsearch/content/EsUnequivalentContentSearcher.java
atlas-api/src/main/java/org/atlasapi/elasticsearch/content/SherlockContentTitleSearcher.java
atlas-api/src/main/java/org/atlasapi/query/v5/search/SearchController.java
atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockAttributes.java
atlas-api/src/main/java/org/atlasapi/query/v5/search/attribute/SherlockParameter.java

Use specific split Sherlock content indices when known instead of wildcards.
Added location provider name filter to v5 Sherlock search endpoint.

Sherlock split index improvement

---

atlas-api/src/main/java/org/atlasapi/output/annotation/DescriptionAnnotation.java

Use same logic as is done for location durations

Fix item-level duration serialization in api

---

atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java

See code comments for more detail but this makes merging logic fill in hierarchy more sensibly from items (and their subclasses) along with for top-level series.
The motivation for this is to allow overrides to not ruin the underlying hierarchy of content; an override series without hierarchy is indistinguishable from a top-level series and would otherwise remove underlying hierarchy, and parentless episodes would have avoided any series parent from being merged in if it existed with the current logic.
Note for episodes we don't merge in container and series parent independently since it is nonsensical; instead we pick the first piece of content that has either value and treat them as a pair.
This change essentially changes merging logic behaviour of top-level series which are equived to …

Merge parent hierarchy

---

atlas-api/src/main/java/org/atlasapi/output/annotation/DescriptionAnnotation.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/annotation/ImagesAnnotation.java
atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java
atlas-core/src/main/java/org/atlasapi/content/Image.java
atlas-core/src/main/java/org/atlasapi/output/OutputContentMerger.java
atlas-core/src/test/java/org/atlasapi/output/OutputContentMergerTest.java

The images set now includes all images from all equivs since it was a promised feature and to make it more consistent with merging of other collection fields.
If the content's image field is not set or is an unavailable image, an available image can now be chosen for it from the images set. In particular this allows another image from the same source to take the place of the expired image, instead of a lower precedent source image being chosen.
Unavailable images are now excluded from the images set as well unless a new all_images annotation is used.

Image merging rework (ENG-1023)

---

atlas-api/src/main/java/org/atlasapi/AtlasPersistenceModule.java
atlas-api/src/main/java/org/atlasapi/output/annotation/BaseChannelGroupsAnnotation.java
atlas-api/src/main/java/org/atlasapi/query/QueryModule.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/OutputChannelGroupResolver.java
atlas-api/src/test/java/org/atlasapi/query/v4/schedule/OutputChannelGroupResolverTest.java
atlas-core/src/main/java/org/atlasapi/annotation/Annotation.java
atlas-core/src/main/java/org/atlasapi/channel/ChannelGroup.java
atlas-core/src/main/java/org/atlasapi/channel/NumberedChannelGroup.java
atlas-core/src/main/java/org/atlasapi/channel/Platform.java
atlas-core/src/main/java/org/atlasapi/channel/Region.java
atlas-core/src/main/java/org/atlasapi/channel/ResolvedChannelGroup.java
atlas-core/src/test/java/org/atlasapi/channel/NumberedChannelGroupTest.java
atlas-core/src/test/java/org/atlasapi/content/BroadcastAggregatorTest.java
atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyChannelGroupTransformer.java
atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyChannelGroupTransformerTest.java
pom.xml

* Added channelNumbersFrom field to NumberedChannelGroup
* Added a new ChannelGroupResolver used for API output which dynamically populates the channel numbers from the specified group when this field is set.
* Added a base_channel_groups annotation to expose this field in the API for use in the channel grouping frontend tool.

Support dynamic channel numbers for certain channel groups

---

atlas-api/src/main/java/org/atlasapi/output/annotation/PlatformAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/annotation/RegionsAnnotation.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java
atlas-core/src/main/java/org/atlasapi/channel/Region.java
atlas-legacy/src/test/java/org/atlasapi/system/legacy/LegacyChannelGroupTransformerTest.java

Allow platform field to be nullable since it can be in Owl and since YouView JSON regions do not have a platform.
Make platform and region annotation use match the class of the same name, switching class behaviour as appropriate.

Fix platform annotation

---

atlas-api/src/main/java/org/atlasapi/output/annotation/ChannelGroupAdvertisedChannelsAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/annotation/ChannelGroupChannelIdsAnnotation.java
atlas-api/src/main/java/org/atlasapi/output/annotation/ChannelGroupChannelsAnnotation.java
atlas-api/src/main/java/org/atlasapi/query/QueryWebModule.java
atlas-api/src/main/java/org/atlasapi/query/v4/channel/ChannelQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutor.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/NoOpChannelGroupResolver.java
atlas-api/src/main/java/org/atlasapi/query/v4/schedule/OutputChannelGroupResolver.java
atlas-api/src/test/java/org/atlasapi/query/v4/channel/ChannelQueryExecutorTest.java
atlas-api/src/test/java/org/atlasapi/query/v4/channelgroup/ChannelGroupQueryExecutorTest.java
atlas-api/src/test/java/org/atlasapi/query/v4/schedule/OutputChannelGroupResolverTest.java
atlas-core/src/main/java/org/atlasapi/channel/ChannelGroup.java
atlas-core/src/main/java/org/atlasapi/channel/ChannelGroupResolver.java
atlas-core/src/main/java/org/atlasapi/channel/NumberedChannelGroup.java
atlas-core/src/main/java/org/atlasapi/channel/Platform.java
atlas-core/src/main/java/org/atlasapi/channel/Region.java
atlas-core/src/main/java/org/atlasapi/content/BroadcastAggregator.java
atlas-core/src/main/java/org/atlasapi/content/ChannelsBroadcastFilter.java
atlas-core/src/main/java/org/atlasapi/criteria/attribute/Attributes.java
atlas-core/src/main/java/org/atlasapi/entity/IdResolver.java
atlas-core/src/test/java/org/atlasapi/content/BroadcastAggregatorTest.java
atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyChannelGroupResolver.java
atlas-legacy/src/main/java/org/atlasapi/system/legacy/LegacyChannelResolver.java

* Improve resolving efficiency of channel group endpoint by adding filtering within the resolve step instead of resolving all groups and then filtering
* Removed a setter on the channel group class and replaced with a copy method to avoid possible side-effects when filtering channels in the channel group endpoint due to caching
* Fixed a possible bug with selections on channel groups when the selection would happen before a further filtering step
* Return correct results count in channel group endpoint
* Throw exceptions when requesting single id in channel and channel group endpoints if no read access
* Expose resource not found error in channel and channel group endpoints to match content endpoint behaviour
* Removed nonsensical lcnSharing boolean from a method on ChannelGroup
* Added …

Channel and channel group endpoint improvements

---

atlas-core/src/main/java/org/atlasapi/equivalence/AbstractEquivalenceGraphStore.java
atlas-core/src/main/java/org/atlasapi/equivalence/EquivalenceGraphStore.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/ContentBootstrapListener.java
atlas-processing/src/main/java/org/atlasapi/system/bootstrap/workers/DirectAndExplicitEquivalenceMigrator.java

In addition to forcing content updates.
It has been observed that outgoing equiv links do not always end up as incoming equiv links on the corresponding piece of content when equivs are migrated. This endpoint allows us to fix such cases as we discover them until the root cause is solved.

Make force migration endpoint also force equiv updates
